---
name: Build & Deploy Lambda

env:
  ARTIFACT_NAME: csye6225-lambda-${{ github.run_number }}.jar
  AWS_REGION: us-east-1

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: |
        echo "${{ env.ARTIFACT_NAME }}"
        mvn package
        ls -al target
    
    - name: Build Deployment Artifact
      run: |
        cd target
        mv lambda-0.0.1-SNAPSHOT.jar ${{env.ARTIFACT_NAME}}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Copy Artifact to S3
      run: |
        cd target
        aws s3 cp ${{env.ARTIFACT_NAME}} s3://${{ secrets.S3_CODEDEPLOY_BUCKET }}
    - name: Lambda API call
      run: aws lambda update-function-code --function-name  emailOnSNS  --s3-bucket ${{ secrets.S3_CODEDEPLOY_BUCKET }} --s3-key ${{env.ARTIFACT_NAME}} --region ${{ env.AWS_REGION }} > log.txt

